{
 "title": "Network",
 "description": "https://github.com/syepes/network_exporter/",
 "tags": [
  "Prometheus",
  "Router"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "station",
    "label": "Station",
    "query": {
     "query": "label_values(ping_loss_percent, host)"
    }
   },
   {
    "name": "name_icmp",
    "label": "Target ICMP",
    "query": {
     "query": "label_values(ping_loss_percent{host=~\"$station\"}, name)"
    }
   },
   {
    "name": "name_mtr",
    "label": "Target MTR",
    "query": {
     "query": "label_values(mtr_hops{host=~\"$station\"}, name)"
    }
   },
   {
    "name": "name_tcp",
    "label": "Target TCP",
    "query": {
     "query": "label_values(tcp_connection_status{host=~\"$station\"}, name)"
    }
   },
   {
    "name": "name_http",
    "label": "Target HTTP",
    "query": {
     "query": "label_values(http_get_status{host=~\"$station\"}, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "iPerf", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Download Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(iperf3_received_bytes * 8) / iperf3_received_seconds",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Upload Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(iperf3_sent_bytes * 8) / iperf3_sent_seconds",
     "legendFormat": "{{target}}"
    }
   ]
  },
  { "title": "ICMP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Standard Deviation Statistics (Jitter)",
   "type": "timeseries",
   "description": "- SD: Squared deviation\n- USD: Standard deviation without correction\n- CSD: Standard deviation with correction (Bessel's)\n- RANGE: Max-Min value range",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "last_over_time(ping_rtt_seconds{host=~\"$station\", name=~\"$name_icmp\", type=\"sd\"}[$__rate_interval])",
     "legendFormat": "SD"
    },
    {
     "expr": "last_over_time(ping_rtt_seconds{host=~\"$station\",name=~\"$name_icmp\", type=\"usd\" }[$__rate_interval])",
     "legendFormat": "USD"
    },
    {
     "expr": "last_over_time(ping_rtt_seconds{host=~\"$station\",name=~\"$name_icmp\", type=\"csd\" }[$__rate_interval])",
     "legendFormat": "CSD"
    },
    {
     "expr": "last_over_time(ping_rtt_seconds{host=~\"$station\",name=~\"$name_icmp\", type=\"range\" }[$__rate_interval])",
     "legendFormat": "RANGE"
    }
   ]
  },
  {
   "title": "Response time / Packet loss ($station)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min_over_time(ping_rtt_seconds{host=~\"$station\", name=~\"$name_icmp\", type=\"best\"}[$__interval])",
     "legendFormat": "best"
    },
    {
     "expr": "avg_over_time(ping_rtt_seconds{host=~\"$station\", name=~\"$name_icmp\", type=\"mean\"}[$__interval])",
     "legendFormat": "mean"
    },
    {
     "expr": "max_over_time(ping_rtt_seconds{host=~\"$station\", name=~\"$name_icmp\", type=\"worst\"}[$__interval])",
     "legendFormat": "worst"
    },
    {
     "expr": "ping_loss_percent{host=~\"$station\",name=~\"$name_icmp\"}",
     "legendFormat": "loss"
    }
   ]
  },
  {
   "title": "Packet loss (All)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ping_loss_percent{host=~\"$station\"} < 100 > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Packet loss per Location",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ping_loss_percent{name=~\"$name_icmp\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Response time per Location",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(ping_rtt_seconds{name=~\"$name_icmp\", type=\"mean\"}[$__interval])) by (host)",
     "legendFormat": "mean - {{host}}"
    }
   ]
  },
  { "title": "MTR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Hops",
   "type": "stat",
   "description": "Number of network HOPS",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mtr_hops{host=~\"$station\",name=~\"$name_mtr\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "MTR - Mean",
   "type": "timeseries",
   "description": "Mean Response time",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort(avg_over_time(mtr_rtt_seconds{host=~\"$station\",name=~\"$name_mtr\", type=\"mean\"}[$__interval]))",
     "legendFormat": "{{ttl}} - {{path}}"
    }
   ]
  },
  {
   "title": "MTR - Loss",
   "type": "timeseries",
   "description": "Packet loss in percent",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sort(avg_over_time(mtr_rtt_seconds{host=~\"$station\",name=~\"$name_mtr\", type=\"loss\"}[$__interval]))",
     "legendFormat": "{{ttl}} - {{path}}"
    }
   ]
  },
  {
   "title": "Hops - Changes",
   "type": "timeseries",
   "description": "Number of network HOPS Changes",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "changes(mtr_hops{name=~\"$name_mtr\"}[$__interval]) > 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 10, "w": 2, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "tcp_connection_status{host=~\"$station\",name=~\"$name_tcp\"}",
       "legendFormat": "{{target}}:{{port}}"
      }
     ]
    },
    {
     "title": "Connection time",
     "type": "timeseries",
     "description": "Response time",
     "gridPos": { "h": 10, "w": 22, "x": 2, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg_over_time(tcp_connection_seconds{host=~\"$station\",name=~\"$name_tcp\"}[$__interval])",
       "legendFormat": "{{target}}:{{port}}"
      }
     ]
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "HTTP Get",
   "type": "timeseries",
   "description": "Download Drilldown",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(http_get_seconds{host=~\"$station\", name=~\"$name_http\"}[$__interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "HTTP Get - Time",
   "type": "timeseries",
   "description": "Total Download time",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(http_get_seconds{name=~\"$name_http\", type=\"Total\"}[$__interval])",
     "legendFormat": "{{station}}"
    }
   ]
  },
  {
   "title": "HTTP Get - Speed",
   "type": "timeseries",
   "description": "Download Speed",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "max(http_get_content_bytes{name=\"$name_http\"}) by (host) / on (host) avg_over_time(http_get_seconds{type=\"Total\",name=\"$name_http\"}[$__interval])",
     "legendFormat": "{{station}}"
    }
   ]
  },
  {
   "title": "Exporter Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "Target Status by Type",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "ping_up{}", "legendFormat": "ICMP - {{host}}" },
      { "expr": "mtr_up{}", "legendFormat": "MTR - {{host}}" },
      { "expr": "tcp_up{}", "legendFormat": "TCP - {{host}}" },
      { "expr": "http_get_up{}", "legendFormat": "HTTPGet - {{host}}" }
     ]
    },
    {
     "title": "Active Targets by Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sum(ping_targets{}) by (host)", "legendFormat": "ICMP - {{host}}" },
      { "expr": "sum(mtr_targets{}) by (host)", "legendFormat": "MTR - {{host}}" },
      { "expr": "sum(tcp_targets{}) by (host)", "legendFormat": "TCP - {{host}}" },
      {
       "expr": "sum(http_get_targets{}) by (host)",
       "legendFormat": "HTTPGet - {{host}}"
      }
     ]
    },
    {
     "title": "go goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(go_goroutines{host=\"$station\"}) by (host)",
       "legendFormat": "{{station}}"
      }
     ]
    },
    {
     "title": "go process resident memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{host=\"$station\"}",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  }
 ]
}