# General
conf:
  refresh: 15m
  nameserver: 10.0.0.1:53 # Optional
  nameserver_timeout: 250ms # Optional
# Specific Protocol settings
icmp:
  interval: 5s
  timeout: 2s
  count: 6
mtr:
  interval: 5s
  timeout: 1000ms
  max-hops: 15
  count: 6
tcp:
  interval: 5s
  timeout: 2s
http_get:
  interval: 10m
  timeout: 15s
# Target list and settings
targets:
  - name: internal
    host: localhost
    type: ICMP+MTR
  - name: google-dns2
    host: 8.8.4.4
    type: ICMP+MTR
  - name: cloudflare-dns
    host: 1.1.1.1
    type: ICMP+MTR
  - name: quad9-dns
    host: 9.9.9.9
    type: ICMP+MTR
  - name: vkontakte
    host: vk.com
    type: ICMP+MTR
  - name: download-file-64M
    host: http://test-debit.free.fr/65536.rnd
    type: HTTPGet
